# https://mcr.microsoft.com/v2/devcontainers/rust/tags/list
FROM mcr.microsoft.com/devcontainers/rust:1-bookworm

# Add any additional dependencies or custom setup here
RUN apt-get update && apt-get install -y libssl-dev pkg-config && apt-get clean
